### ISSUE TITLE
How to resize space between 2 buttons in ACSPinNumberPadCircleView

### ISSUE THREAD

**Issue by ishrek** [arconsis/ACSPinKit#1]
I want distance between two smaller buttons
 Example 
   Button 0 < 5pixel > Button 1 <5pixel> Button 2
->>>  i want Button 0 <2pixel> Button 1 <2pixel> Button 2  but Size button not changed

**Comment by orschaef** [comment]
Hi,

thanks for your input.

As you can see in `ACSPinNumberPadCircleView` the buttons are layouted via Auto Layout. Regarding different screen sizes we have not set fixed pixel spaces. Instead the buttons are layouted dynamically. Just have a look at the `updateConstraints` method.

With the latest releases of iOS and UIKit we would use `UIStackView` to achieve that - which was not available at the time of the first development steps of this library.

Currently there are no plans to change the layout logic in the near future. Feel free to make a PR to add support for any layout customization. But I think this is hard to achieve and you always run into trade offs when making usage very convenient and provide many customization possibilities at the same time.

Cheers,
Orlando
