### ISSUE TITLE
How to get rootViewController when Presented a view

### ISSUE THREAD

**Issue by ishrek** [arconsis/ACSPinKit#2]
i use xib file. How to get root view controller when un-lock passcode successfull or how to close VerifilefullScreen view and return view before click home button

**Comment by orschaef** [comment]
Could you please go more into details? What are you trying to achieve, what do you mean with "before clicking the home button"?

At first glance I think you don't have a problem with ACSPinKit - instead its about general presentations of other view controllers in connection with the VerifyFullScreenController?

Cheers
Orlando

**Comment by ishrek** [comment]
i fixed this issuse.  thank you very much.

**Comment by Alifar** [comment]
@ishrek how did you solved this problem? I have the same and I am using tabbar application with navigation bars. After entering the pin code it always goes to the first tab.

**Comment by ishrek** [comment]
@Alifar  i created a customWindow (UIWindow) above self.window . And add passcode view to customWindow. When verify successed then dismiss customWindow

1 .In AppDelegate : ` @property (strong, nonatomic) UIWindow *secondWindow;`
2. In applicationWillResignActive function : Store rootViewController of self.window
`- (void)applicationWillResignActive:(UIApplication *)application {
    //Get current view controller
    NSString *currentClass = NSStringFromClass([[[[UIApplication sharedApplication] delegate] window].rootViewController class]);
    if (![currentClass isEqualToString:@"SCPinViewController"]) {
        currentController = [[[UIApplication sharedApplication] delegate] window].rootViewController;
    }
    NSLog(@"%@", [currentController class]);
}`
3. In applicationWillEnterForeground function. Show customWindow
` 
        
        if (!self.secondWindow) {
            self.secondWindow = [[UIWindow alloc] initWithFrame:self.window.frame];
            [self.secondWindow setBackgroundColor:[UIColor clearColor]];
        }
        
        //Check Window level alert or Keyboard
        //        if ([KeyboardStateListener sharedInstance].isVisible) {
        NSArray *windows = [[UIApplication sharedApplication] windows];
        UIWindow *lastWindow = (UIWindow *)[windows lastObject];
        [self.secondWindow setWindowLevel:lastWindow.windowLevel + 1];
        //        }else {
        //            [self.secondWindow setWindowLevel:UIWindowLevelAlert];
        //        }
        double delayInSeconds = 0.5f;
        dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, delayInSeconds * NSEC_PER_SEC);
        dispatch_after(popTime, dispatch_get_main_queue(), ^(void) {
            if (profileData.pinCode.length == 4) {
                self.secondWindow.rootViewController = [self pincodeController];
                [self.secondWindow makeKeyAndVisible];
            }
        });
   `

**Comment by orschaef** [comment]
Just a quick thought: If you just hold a reference to your rootViewController (TabBarController or whatever) and use it for window.rootViewController assignments - this doesn't work? Maybe I still don't  get the problem ... If you need further assistance or if this is an ACSPinKit related issue please provide me a detailed example project. 

Thanks and Cheers 🍺
