### ISSUE TITLE
How to click Home button when show Passcode view and App hang up

### ISSUE THREAD

**Issue by ishrek** [arconsis/ACSPinKit#3]
I proteced : when showed touch id view then not click home button. 

But i protected new issuse in your Libary

Action

1.Go to App
2.Enable passcode and touch ID
3.Click Home button
4. Hold down finger point in home button and in same times tap to Touch ID app

Actual
App opened success but show Touch ID view. And Click to Enter Passcode or Cancel button then App hang up

Expect
App not hang up and dississ Touch ID view

Please help me

**Comment by orschaef** [comment]
Sorry for the very late response. I didn't realize that the ticket was reopened by you.
I hope I will find some time to investigate that issue soon.
Stay tuned...

(Or maybe you already found the problem?)

**Comment by wfrank2509** [comment]
I guess this ticket is not relevant anymore.
