### ISSUE TITLE
titleImage size problem

### ISSUE THREAD

**Issue by sumowesley** [arconsis/ACSPinKit#4]
I am setting the titleImage using the following code:
```
self.pinController.pinCustomizer.titleImage = [UIImage imageNamed:@"wst_pin"];
```
When a PIN screen is shown, the image is tiny in comparison to the image in the project (200x60). I have tried with an image of 60x60 and I still have the same issue. The partial screen shot is from the simulator (IOS10, iPhone 6s) and the result is the same on a device.
![acspinkit_titleimage_001](https://cloud.githubusercontent.com/assets/5694619/19417387/63b39c96-93a3-11e6-8ceb-f4bc8056a686.jpg)

Is there a way to force the image size? I'm using Xcode 8.0 with IOS 10 as the target.

**Comment by sumowesley** [comment]
Height seems to be constrained - I reduce height to 20 pixels and I get something wider.

**Comment by orschaef** [comment]
Yes, as you found out - this is the expected behaviour. Somehow we have to ensure that the interface keeps looking good and that the image does not break the rest of the UI elements.

**Comment by sumowesley** [comment]
What is the maximum height of the image element?

**Comment by orschaef** [comment]
Hey,

have a look at `ACSPinDisplayFullscreenView.m` where the layout constraints are set.
Then you will see that the image view is constrained to a maximum vertical size of 30.
But if you want to understand the whole layout logic you have to look at all constraints.

Just a friendly reminder - this is an open source project. Everyone has the possibility to look into the code. With keeping that in mind you can answer many of your questions yourself.
