### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by maxkramerbcgdv** [arconsis/ACSPinKit#5]
Hi,

I've been using your framework which has been great and is definitely one of the best alternatives out there!

We've just switched over from Cocoapods to Carthage but I realised today that it is not fully supported by ACSPinKit. When running `carthage build` we are presented with an error regarding Carthage attempting to build the wrong scheme:

> A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/kramer_max/Projects/COUP/coup-fieldtool-ios/Carthage/Checkouts/ACSPinKit/Example/ACSPinKit.xcworkspace -scheme FDKeychain-iOS8.0 -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
> xcodebuild: error: Scheme FDKeychain-iOS8.0 is not currently configured for the clean action.

As you can see, the xcrun/xcodebuild command is using the `FDKeychain-iOS8.0` scheme rather than the `ACSPinKit` one and is therefore failing. This could be because Carthage hasn't recognized FDKeychain as a dependency?

**Comment by orschaef** [comment]
Hi,

thanks for filing this issue.

Currently we do not support Carthage and haven't tested the integration of ACSPinKit with it.
At times we initially build ACSPinKit Carthage was not a visible tool at all.
Right now we rarely find time to keep this framework updated - but feel free to make a pull request which fixes the issue.

Cheers 🍻
Orlando

**Comment by maxkramerbcgdv** [comment]
Alright, I've opened an issue over at Carthage as it's a carthage issue: https://github.com/Carthage/Carthage/issues/1541

**Comment by orschaef** [comment]
Should be fixed with (as you can read here: #1541). I close this issue for now - check back if you still encounter this problem.
