### ISSUE TITLE
Data Encryption

### ISSUE THREAD

**Issue by SSDIAshokPathak** [arconsis/ACSPinKit#8]
Dear ,

Thank you for your support.

I just want to know that is this library using any Data Encryption processing (like "AES", "3DES", "RSA", "DH" etc), if yes could you please give some information about it, if possible.

Thanks in advance.

**Comment by orschaef** [comment]
Sorry for the late response. Only Access to the default keychain (via FDKeychain) is implemented. No other encryption method is used...
